import { RestaurantSettings, MenuCategory, MenuItem, CustomerStory, GalleryItem } from '../types';

export const INITIAL_RESTAURANT_SETTINGS: RestaurantSettings = {
  name: "Dream Love Cafe & Restaurant",
  tagline: "Multi-Cuisine Family Cafe & Restaurant",
  cuisines: ["Indian", "Tandoor", "Chinese", "Biryani"],
  phone: "+91 99333 88167",
  whatsapp: "+919933388167",
  address: "QPHM+8QV Central Bus Stand, Contai Bypass Rd, opposite Jawed Habib's, Kishore Nagar Garh, Kanthi Baliari, Contai, West Bengal 721404",
  plusCode: "QPHM+8QV Contai, West Bengal",
  googleMapsCid: "16143850601250640223",
  googleMapsUrl: "https://maps.google.com/?cid=16143850601250640223",
  openingHours: "Monday - Sunday: 12:00 PM - 12:00 AM",
  priceRangeForTwo: "₹200 - ₹400",
  diningModes: ["Dine-in", "Takeaway", "No-contact Delivery"],
  googleRating: 4.1,
  googleReviewsCount: 96,
  googleReviewsUrl: "https://maps.google.com/?cid=16143850601250640223",
  instagramUrl: "https://instagram.com",
  facebookUrl: "https://facebook.com",
  orderInstructions: "Place your order via WhatsApp for quick confirmation or select Takeaway/Delivery during checkout.",
  reservationInstructions: "Reserve your table online or call us directly. Table holds for 15 minutes past reserved time.",
};

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "cat-1",
    slug: "chef-specials",
    name: "Chef Specials & Main Dishes",
    description: "Signature curries, slow-cooked delicacies, and specialty main courses.",
    icon: "UtensilsCrossed",
    displayOrder: 1,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cat-2",
    slug: "tandoori-kebabs",
    name: "Tandoori & Kebabs",
    description: "Authentic clay-oven roasted meats and sizzling pan kebabs.",
    icon: "Flame",
    displayOrder: 2,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cat-3",
    slug: "starters-bites",
    name: "Starters & Quick Bites",
    description: "Crispy appetizers, classic fried finger foods, and street-style bites.",
    icon: "Popcorn",
    displayOrder: 3,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cat-4",
    slug: "breads-kulchas",
    name: "Breads & Kulchas",
    description: "Freshly baked tandoori rotis, buttery naans, and stuffed kulchas.",
    icon: "Wheat",
    displayOrder: 4,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cat-5",
    slug: "chinese-noodles-rice",
    name: "Chinese, Noodles & Fried Rice",
    description: "Wok-tossed noodles, aromatic fried rice, chopsueys, and hot soups.",
    icon: "CookingPot",
    displayOrder: 5,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cat-6",
    slug: "beverages-shakes-mocktails",
    name: "Beverages, Shakes & Mocktails",
    description: "Refreshing mocktails, thick milkshakes, fresh juices, and hot teas.",
    icon: "GlassWater",
    displayOrder: 6,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Chef Specials & Main Dishes
  {
    id: "m-1",
    name: "Chicken Vorta",
    category: "chef-specials",
    description: "Signature shredded chicken cooked in rich egg-infused velvety gravy.",
    price: 270,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 1,
  },
  {
    id: "m-2",
    name: "Kadhai Mutton",
    category: "chef-specials",
    description: "Spicy thick gravy cooked with tender mutton chunks and bell peppers.",
    price: 395,
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 2,
  },
  {
    id: "m-3",
    name: "Mutton Kasa",
    category: "chef-specials",
    description: "Slow-cooked Bengali style dark spicy mutton gravy infused with mustard and whole spices.",
    price: 360,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 3,
  },
  {
    id: "m-4",
    name: "Chicken Hyderabadi",
    category: "chef-specials",
    description: "Rich spiced green gravy flavored with fresh coriander, mint, and aromatic spices.",
    price: 235,
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 4,
  },
  {
    id: "m-5",
    name: "Dream Love Special Handi Chicken Biriyani",
    category: "chef-specials",
    description: "Fragrant basmati rice dum cooked with marinated chicken in traditional sealed clay pot.",
    priceRange: "₹220–₹260",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 5,
  },
  {
    id: "m-6",
    name: "Chicken Biriyani",
    category: "chef-specials",
    description: "Classic Kolkata style biryani with succulent chicken piece, boiled egg, and soft potato.",
    price: 160,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 6,
  },
  {
    id: "m-7",
    name: "Mutton Biriyani",
    category: "chef-specials",
    description: "Slow cooked tender mutton dum biryani with seasoned potato and boiled egg.",
    price: 395,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 7,
  },
  {
    id: "m-8",
    name: "Steamed Rice",
    category: "chef-specials",
    description: "Long grain aromatic basmati rice cooked to fluffy perfection.",
    price: 80,
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 8,
  },

  // Tandoori & Kebabs
  {
    id: "m-9",
    name: "Tandoori Chicken Masala",
    category: "tandoori-kebabs",
    description: "Smoky tandoori chicken simmered in rich tomato gravy.",
    portion: "Half / Full",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 9,
  },
  {
    id: "m-10",
    name: "Tandoori Butter Chicken",
    category: "tandoori-kebabs",
    description: "Classic charcoal-smoked chicken pieces in velvety butter cream gravy.",
    portion: "Half / Full",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 10,
  },
  {
    id: "m-11",
    name: "Tandoori Kadai Chicken",
    category: "tandoori-kebabs",
    description: "Tandoor roasted chicken tossed with freshly ground spices and bell peppers.",
    portion: "Half / Full",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 11,
  },
  {
    id: "m-12",
    name: "Paper Tandoori Chicken",
    category: "tandoori-kebabs",
    description: "Thin paper-style wrapped whole spiced chicken roasted crisp in the clay oven.",
    portion: "Half / Full",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 12,
  },
  {
    id: "m-13",
    name: "Chicken Tikka & Tangri Kabab",
    category: "tandoori-kebabs",
    description: "Char-grilled boneless chicken tikka paired with marinated spiced chicken drumsticks.",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 13,
  },
  {
    id: "m-14",
    name: "Dream Love Special Pan Kabab",
    category: "tandoori-kebabs",
    description: "House special shallow-fried marinated minced chicken patties served hot with mint chutney.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 14,
  },
  {
    id: "m-15",
    name: "Dream Love Special Chicken Kuttu Parotta",
    category: "tandoori-kebabs",
    description: "Shredded layered parotta tossed with spiced chicken, eggs, and rich gravy.",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 15,
  },
  {
    id: "m-16",
    name: "Tandoori Fish & Fish Tikka",
    category: "tandoori-kebabs",
    description: "Fresh fish fillets marinated in hung curd and carom seeds, roasted over hot coals.",
    portion: "As per size",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 16,
  },

  // Starters & Quick Bites
  {
    id: "m-17",
    name: "Chicken Lollipop & Schezwan Lollipop",
    category: "starters-bites",
    description: "Crispy fried chicken wings tossed in hot garlic Schezwan sauce.",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 17,
  },
  {
    id: "m-18",
    name: "Chicken 65",
    category: "starters-bites",
    description: "Spicy deep-fried chicken cubes tossed with curry leaves, red chilies, and yogurt.",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 18,
  },
  {
    id: "m-19",
    name: "Paneer 65",
    category: "starters-bites",
    description: "Crispy cottage cheese cubes tossed in spicy South Indian seasoning and herbs.",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 19,
  },
  {
    id: "m-20",
    name: "Gobi 65",
    category: "starters-bites",
    description: "Batter-fried cauliflower florets seasoned with aromatic spices.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 20,
  },
  {
    id: "m-21",
    name: "Mushroom 65",
    category: "starters-bites",
    description: "Crispy mushrooms fried with ginger, garlic, and curry leaves.",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 21,
  },
  {
    id: "m-22",
    name: "Prawn 65",
    category: "starters-bites",
    description: "Juicy prawns marinated in hot spices and fried until golden crispy.",
    image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 22,
  },
  {
    id: "m-23",
    name: "Chicken Pakora",
    category: "starters-bites",
    description: "Bengali style spiced gram flour batter fried chicken fritters.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 23,
  },
  {
    id: "m-24",
    name: "Crispy Chicken",
    category: "starters-bites",
    description: "Double-crunch breaded fried chicken strips served with house dip.",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 24,
  },
  {
    id: "m-25",
    name: "Drumsticks",
    category: "starters-bites",
    description: "Crispy fried spiced chicken drumsticks served with chili garlic sauce.",
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 25,
  },
  {
    id: "m-26",
    name: "Fish Finger",
    category: "starters-bites",
    description: "Crumbed fish strips fried crisp and served with tartar sauce.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 26,
  },
  {
    id: "m-27",
    name: "Fish Fry",
    category: "starters-bites",
    description: "Classic Kolkata Bhetki fish fry served with mustard dip (Kasundi).",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 27,
  },
  {
    id: "m-28",
    name: "French Fries",
    category: "starters-bites",
    description: "Golden crisp potato fries lightly salted.",
    image: "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 28,
  },

  // Breads & Kulchas
  {
    id: "m-29",
    name: "Tandoori Roti",
    category: "breads-kulchas",
    description: "Whole wheat flatbread baked in the clay tandoor.",
    price: 25,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 29,
  },
  {
    id: "m-30",
    name: "Tandoori Butter Roti",
    category: "breads-kulchas",
    description: "Whole wheat tandoori roti brushed generously with butter.",
    price: 35,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 30,
  },
  {
    id: "m-31",
    name: "Tandoori Plain Naan",
    category: "breads-kulchas",
    description: "Soft leavened white flour bread baked in tandoor.",
    price: 40,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 31,
  },
  {
    id: "m-32",
    name: "Tandoori Butter Naan",
    category: "breads-kulchas",
    description: "Fluffy tandoori naan brushed with rich butter.",
    price: 50,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    displayOrder: 32,
  },
  {
    id: "m-33",
    name: "Garlic Naan",
    category: "breads-kulchas",
    description: "Tandoori naan topped with chopped minced garlic and coriander.",
    price: 60,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 33,
  },
  {
    id: "m-34",
    name: "Butter Garlic Naan",
    category: "breads-kulchas",
    description: "Garlic naan finished with a rich glaze of melted butter.",
    price: 70,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    displayOrder: 34,
  },
  {
    id: "m-35",
    name: "Chicken Kulcha with Butter",
    category: "breads-kulchas",
    description: "Soft bread stuffed with spiced minced chicken and topped with butter.",
    price: 90,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 35,
  },
  {
    id: "m-36",
    name: "Plain Kulcha",
    category: "breads-kulchas",
    description: "Traditional soft Punjabi style flatbread.",
    price: 45,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 36,
  },
  {
    id: "m-37",
    name: "Butter Kulcha",
    category: "breads-kulchas",
    description: "Soft kulcha brushed generously with butter.",
    price: 55,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 37,
  },
  {
    id: "m-38",
    name: "Laccha Paratha",
    category: "breads-kulchas",
    description: "Crispy multi-layered tandoori whole wheat paratha.",
    price: 40,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 38,
  },

  // Chinese, Noodles & Fried Rice
  {
    id: "m-39",
    name: "Schezwan Egg Chowmein",
    category: "chinese-noodles-rice",
    description: "Spicy wok-tossed noodles with scramble eggs, veggies, and Schezwan sauce.",
    price: 145,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 39,
  },
  {
    id: "m-40",
    name: "Paneer Fried Rice",
    category: "chinese-noodles-rice",
    description: "Aromatic rice tossed with fried cottage cheese cubes and fresh vegetables.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 40,
  },
  {
    id: "m-41",
    name: "Mushroom Fried Rice",
    category: "chinese-noodles-rice",
    description: "Wok-fried rice tossed with sliced button mushrooms and spring onions.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 41,
  },
  {
    id: "m-42",
    name: "Chicken Fried Rice",
    category: "chinese-noodles-rice",
    description: "Classic Chinese wok-fried basmati rice with shredded chicken and eggs.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 42,
  },
  {
    id: "m-43",
    name: "Schezwan Mix Fried Rice",
    category: "chinese-noodles-rice",
    description: "Spicy Schezwan rice loaded with chicken, prawns, egg, and veggies.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    displayOrder: 43,
  },
  {
    id: "m-44",
    name: "Chinese Chopsuey",
    category: "chinese-noodles-rice",
    description: "Crispy fried noodles topped with savory soy-glazed chicken and vegetable sauce.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 44,
  },
  {
    id: "m-45",
    name: "American Chopsuey",
    category: "chinese-noodles-rice",
    description: "Crispy noodles topped with tangy sweet and sour tomato chicken gravy and fried egg.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 45,
  },
  {
    id: "m-46",
    name: "Chicken Manchow Soup",
    category: "chinese-noodles-rice",
    description: "Hot garlic chicken broth with minced vegetables served with crispy fried noodles.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 46,
  },
  {
    id: "m-47",
    name: "Hot & Sour Chicken Soup",
    category: "chinese-noodles-rice",
    description: "Tangy and spicy chicken broth infused with vinegar, white pepper, and mushrooms.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 47,
  },
  {
    id: "m-48",
    name: "Sweet Corn Veg Soup",
    category: "chinese-noodles-rice",
    description: "Comforting thick vegetable soup with sweet corn kernels.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 48,
  },
  {
    id: "m-49",
    name: "Tom Yum Soup",
    category: "chinese-noodles-rice",
    description: "Thai style hot lemongrass and galangal infused clear spicy soup.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    displayOrder: 49,
  },

  // Beverages, Shakes & Mocktails
  {
    id: "m-50",
    name: "Dream Love Special Mocktail",
    category: "beverages-shakes-mocktails",
    description: "Signature layered fruit cooler with mint, lime, and crushed ice.",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    displayOrder: 50,
  },
  {
    id: "m-51",
    name: "Blue Lemonade",
    category: "beverages-shakes-mocktails",
    description: "Refreshing blue curaçao flavor mixed with sparkling citrus lemonade.",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 51,
  },
  {
    id: "m-52",
    name: "Green Lemonade",
    category: "beverages-shakes-mocktails",
    description: "Chilled green apple mint cooler with soda fizz.",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 52,
  },
  {
    id: "m-53",
    name: "Orange Fizz",
    category: "beverages-shakes-mocktails",
    description: "Tangy orange juice with sparkling soda and crushed mint.",
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 53,
  },
  {
    id: "m-54",
    name: "Butterscotch Shake",
    category: "beverages-shakes-mocktails",
    description: "Thick creamy butterscotch milkshake with caramel drizzle.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 54,
  },
  {
    id: "m-55",
    name: "Oreo Shake",
    category: "beverages-shakes-mocktails",
    description: "Rich chocolate cookie shake topped with crushed Oreo crumble.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 55,
  },
  {
    id: "m-56",
    name: "Chocolate Shake",
    category: "beverages-shakes-mocktails",
    description: "Classic thick cocoa milkshake topped with whipped cream.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 56,
  },
  {
    id: "m-57",
    name: "Sarja Shake",
    category: "beverages-shakes-mocktails",
    description: "Special dry fruit and mango fusion thick shake.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 57,
  },
  {
    id: "m-58",
    name: "Cold Coffee with Ice Cream",
    category: "beverages-shakes-mocktails",
    description: "Chilled espresso blended with milk and topped with vanilla ice cream scoop.",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    displayOrder: 58,
  },
  {
    id: "m-59",
    name: "Fresh Watermelon Juice",
    category: "beverages-shakes-mocktails",
    description: "Pure chilled watermelon juice squeezed fresh.",
    image: "https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 59,
  },
  {
    id: "m-60",
    name: "Musambi Juice",
    category: "beverages-shakes-mocktails",
    description: "Freshly pressed sweet lime juice with black salt.",
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 60,
  },
  {
    id: "m-61",
    name: "Pineapple Juice",
    category: "beverages-shakes-mocktails",
    description: "Fresh sweet pineapple juice served chilled.",
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 61,
  },
  {
    id: "m-62",
    name: "Masala Tea",
    category: "beverages-shakes-mocktails",
    description: "Aromatic Indian chai brewed with cardamom, ginger, and cloves.",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 62,
  },
  {
    id: "m-63",
    name: "Green Tea",
    category: "beverages-shakes-mocktails",
    description: "Light anti-oxidant rich green tea infusion.",
    image: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 63,
  },
  {
    id: "m-64",
    name: "Espresso",
    category: "beverages-shakes-mocktails",
    description: "Rich dark shot of brewed espresso coffee.",
    image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=600&q=80",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    displayOrder: 64,
  },
];

export const INITIAL_CUSTOMER_STORIES: CustomerStory[] = [
  {
    id: "story-1",
    author: "Rahul S.",
    date: "August 2026",
    rating: 5,
    text: "The Handi Chicken Biriyani and Chicken Vorta were phenomenal. Beautiful warm ambience for evening dining with family in Contai.",
    source: "Customer Story"
  },
  {
    id: "story-2",
    author: "Priya M.",
    date: "July 2026",
    rating: 5,
    text: "Great multi-cuisine menu! Kadhai Mutton was rich and perfectly spiced. Very polite service and clean seating.",
    source: "Customer Story"
  },
  {
    id: "story-3",
    author: "Amit K.",
    date: "June 2026",
    rating: 4,
    text: "Tandoori Butter Naan with Chicken Kulcha is a must try. Fast takeaway packing and prompt response on WhatsApp.",
    source: "Customer Story"
  }
];

export const INITIAL_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "g-1",
    title: "Signature Handi Biriyani",
    category: "Dishes",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1000&q=80",
    caption: "Aromatic dum cooked biryani served in traditional clay pot",
    is_featured: true,
    display_order: 1
  },
  {
    id: "g-2",
    title: "Midnight Café Ambience",
    category: "Ambience",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80",
    caption: "Warm dining space designed for family & friends",
    is_featured: true,
    display_order: 2
  },
  {
    id: "g-3",
    title: "Tandoori Specialties",
    category: "Tandoor",
    image_url: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1000&q=80",
    caption: "Charcoal roasted chicken and kebabs hot from clay oven",
    is_featured: true,
    display_order: 3
  },
  {
    id: "g-4",
    title: "Specialty Mocktails",
    category: "Beverages",
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1000&q=80",
    caption: "Handcrafted refreshing mocktails and shakes",
    is_featured: false,
    display_order: 4
  },
  {
    id: "g-5",
    title: "Chinese Chopsuey & Noodles",
    category: "Chinese",
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=1000&q=80",
    caption: "Freshly tossed noodles and hot Schezwan specials",
    is_featured: false,
    display_order: 5
  },
  {
    id: "g-6",
    title: "Evening Dining Gathering",
    category: "Ambience",
    image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    caption: "Intimate and cozy seating for memorable evenings",
    is_featured: true,
    display_order: 6
  }
];
