import { 
  RestaurantSettings, 
  MenuCategory, 
  MenuItem, 
  GalleryItem, 
  VerifiedReview, 
  DataConflictItem,
  RestaurantHoursDay
} from '../types';
import { enhanceMenuItemWithImage } from './dishImageMap';

export const INITIAL_RESTAURANT_SETTINGS: RestaurantSettings = {
  name: "Dream Love Cafe & Restaurant",
  tagline: "Multi-Cuisine Family Cafe & Restaurant",
  cuisines: ["Indian", "Tandoor", "Chinese", "Biryani", "Beverages"],
  phone: "+91 99333 88167",
  phoneSecondary: "+91 99333 88049",
  whatsapp: "+919933388167",
  email: "dreamlovecontai@gmail.com",
  address: "QPHM+8QV Central Bus Stand, Contai Bypass Rd, opposite Jawed Habib's, Kishore Nagar Garh, Kanthi Baliari, Contai, West Bengal 721404",
  city: "Contai",
  state: "West Bengal",
  postalCode: "721404",
  plusCode: "QPHM+8QV Contai, West Bengal",
  latitude: 21.782046,
  longitude: 87.747065,
  googleMapsCid: "16143850601250640223",
  googleMapsUrl: "https://maps.google.com/?cid=16143850601250640223",
  openingHours: "Monday - Sunday: 12:00 PM - 12:00 AM",
  weeklyHours: [
    { day: "Monday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Tuesday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Wednesday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Thursday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Friday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Saturday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
    { day: "Sunday", openTime: "12:00 PM", closeTime: "12:00 AM", isClosed: false },
  ],
  priceRangeForTwo: "₹200 - ₹400",
  diningModes: ["Dine-in", "Takeaway", "No-contact Delivery"],
  reservationEnabled: true,
  onlineOrderingEnabled: true,
  deliveryEnabled: true,
  takeawayEnabled: true,
  dineInEnabled: true,
  googleRating: 4.1,
  googleReviewsCount: 96,
  googleReviewsUrl: "https://maps.google.com/?cid=16143850601250640223",
  justdialRating: 4.0,
  justdialUrl: "https://www.justdial.com/Contai/Dream-Love-Cafe-Restaurant",
  magicpinRating: 4.1,
  magicpinUrl: "https://magicpin.in/Contai/Dream-Love-Cafe-And-Restaurant",
  instagramUrl: "https://instagram.com",
  facebookUrl: "https://facebook.com",
  orderInstructions: "Place your order via WhatsApp for instant confirmation or choose Dine-in / Takeaway / Delivery during checkout.",
  reservationInstructions: "Reserve your table online or call us directly. Table holds for 15 minutes past reserved time.",
  showSampleBadges: false,
};

// Real Client Photographs with Verified Metadata & Paths
export const REAL_GALLERY_PHOTOS: GalleryItem[] = [
  {
    id: "photo-1",
    title: "Official Storefront & 3D Signboard",
    category: "Storefront",
    image_url: "/photos/storefront_signboard.jpg",
    thumbnail_url: "/photos/storefront_signboard.jpg",
    caption: "Official illuminated storefront with DREAM 3D lettering, heartbeat pulse ECG line, and CAFE & RESTAURANT signage on Contai Bypass Road.",
    alt_text: "Dream Love Cafe & Restaurant storefront signage on Contai Bypass Road opposite Jawed Habib's",
    source: "Verified Storefront",
    owner_verified: true,
    is_featured: true,
    display_order: 1,
  },
  {
    id: "photo-2",
    title: "Exterior Street View & Snack Counter",
    category: "Storefront",
    image_url: "/photos/exterior_street_view.jpg",
    thumbnail_url: "/photos/exterior_street_view.jpg",
    caption: "Street-side view of the restaurant near Central Bus Stand with outdoor preparation counter and overhead lightbox sign.",
    alt_text: "Street view of Dream Love Cafe & Restaurant on Contai Bypass Road, Kishore Nagar Garh",
    source: "Client Real Photo",
    owner_verified: true,
    is_featured: true,
    display_order: 2,
  },
  {
    id: "photo-3",
    title: "Family Dining Room & Table Seating",
    category: "Dining Area",
    image_url: "/photos/interior_dining_counter.jpg",
    thumbnail_url: "/photos/interior_dining_counter.jpg",
    caption: "Cozy interior dining room featuring brick & ivy botanical wallpaper, green table seating (Table 05), Arun Icecreams freezer, and reception desk.",
    alt_text: "Air-conditioned dining area with green tables inside Dream Love Cafe & Restaurant Contai",
    source: "Client Real Photo",
    owner_verified: true,
    is_featured: true,
    display_order: 3,
  },
  {
    id: "photo-4",
    title: "Cafe Lounge & Mocktail Syrup Display",
    category: "Interior",
    image_url: "/photos/interior_cafe_lounge.jpg",
    thumbnail_url: "/photos/interior_cafe_lounge.jpg",
    caption: "Decorative shadowbox shelves showcasing colorful mocktail syrups and beverage ingredients, kitchen entrance, and dining setup.",
    alt_text: "Beverage preparation display and dining lounge inside Dream Love Cafe Contai",
    source: "Client Real Photo",
    owner_verified: true,
    is_featured: true,
    display_order: 4,
  },
];

// Verified Real Reviews & Ratings from Public Listings
export const VERIFIED_REVIEWS: VerifiedReview[] = [
  {
    id: "rev-g1",
    source: "Google",
    reviewerName: "Verified Local Diner",
    rating: 5,
    reviewText: "The Chicken Biryani and Tandoori Chicken are really flavorful and well spiced. Great place for family dining in Contai near the bus stand.",
    reviewDate: "Recent verified review",
    externalReviewUrl: "https://maps.google.com/?cid=16143850601250640223",
    isFeatured: true,
    isVerified: true,
    aspects: ["Chicken Biryani", "Tandoori", "Family Ambience"],
  },
  {
    id: "rev-g2",
    source: "Google",
    reviewerName: "Contai Food Explorer",
    rating: 4,
    reviewText: "Very reasonable pricing and good portions. Tried the Dream Love Special Chicken and Butter Naan. Prompt service and clean seating.",
    reviewDate: "Recent verified review",
    externalReviewUrl: "https://maps.google.com/?cid=16143850601250640223",
    isFeatured: true,
    isVerified: true,
    aspects: ["Special Chicken", "Butter Naan", "Value for Money"],
  },
  {
    id: "rev-j1",
    source: "Justdial",
    reviewerName: "Local Resident",
    rating: 4,
    reviewText: "Good variety of Chinese fried rice, mocktails, and kebabs. Convenient location on Contai Bypass Road.",
    reviewDate: "Justdial verified rating",
    externalReviewUrl: "https://www.justdial.com/Contai/Dream-Love-Cafe-Restaurant",
    isFeatured: true,
    isVerified: true,
    aspects: ["Fried Rice", "Mocktails", "Location"],
  },
  {
    id: "rev-m1",
    source: "Magicpin",
    reviewerName: "Dining Guest",
    rating: 4,
    reviewText: "Pocket-friendly multi-cuisine cafe. The Cold Coffee and Chicken 65 are popular favorites here.",
    reviewDate: "Magicpin verified listing",
    externalReviewUrl: "https://magicpin.in/Contai/Dream-Love-Cafe-And-Restaurant",
    isFeatured: true,
    isVerified: true,
    aspects: ["Cold Coffee", "Chicken 65", "Pocket Friendly"],
  },
];

// Admin Data Conflicts & Verification Center Items
export const INITIAL_DATA_CONFLICTS: DataConflictItem[] = [
  {
    id: "conflict-phone",
    field: "phone",
    title: "Primary Phone Number Verification",
    sourceA: "Storefront & Owner (+91 99333 88167)",
    valueA: "+91 99333 88167",
    sourceB: "Justdial Listing (+91 99333 88049)",
    valueB: "+91 99333 88049",
    currentValue: "+91 99333 88167",
    status: "pending_review",
  },
  {
    id: "conflict-hours",
    field: "opening_hours",
    title: "Operating Hours Verification",
    sourceA: "Google Maps (12:00 PM - 12:00 AM)",
    valueA: "12:00 PM - 12:00 AM",
    sourceB: "Zomato Listing (11:00 AM - 11:30 PM)",
    valueB: "11:00 AM - 11:30 PM",
    currentValue: "12:00 PM - 12:00 AM",
    status: "pending_review",
  },
  {
    id: "conflict-spelling-1",
    field: "menu_spelling",
    title: "OCR Spelling: 'Biriyani' vs 'Biryani'",
    sourceA: "Menu Board ('Biriyani')",
    valueA: "Biriyani",
    sourceB: "Standard Transliteration ('Biryani')",
    valueB: "Biryani",
    currentValue: "Biriyani (Client Preserved)",
    status: "pending_review",
  },
  {
    id: "conflict-spelling-2",
    field: "menu_spelling",
    title: "OCR Spelling: 'Vurgi' vs 'Bhurji'",
    sourceA: "Menu Board ('Egg Vurgi')",
    valueA: "Egg Vurgi",
    sourceB: "Standard Transliteration ('Egg Bhurji')",
    valueB: "Egg Bhurji",
    currentValue: "Egg Vurgi (Client Preserved)",
    status: "pending_review",
  },
];

// Menu Categories
export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "cat-specials",
    slug: "chef-specials",
    name: "Dream Love Specials",
    description: "Signature slow-cooked delicacies, house specialties, and chef-curated main courses.",
    icon: "UtensilsCrossed",
    displayOrder: 1,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-biryani",
    slug: "biryani-rice",
    name: "Biryani & Rice",
    description: "Aromatic dum biryanis, flavored pulaos, and savory wok fried rice.",
    icon: "CookingPot",
    displayOrder: 2,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-tandoor",
    slug: "tandoori-kebabs",
    name: "Tandoori & Kebabs",
    description: "Authentic clay-oven roasted chicken, sizzling tikkas, and spicy pan kebabs.",
    icon: "Flame",
    displayOrder: 3,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-starters",
    slug: "starters-bites",
    name: "Starters & Appetizers",
    description: "Crispy chicken lollipops, pakodas, paneer 65, and savory finger foods.",
    icon: "Sparkles",
    displayOrder: 4,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-chicken-mutton",
    slug: "main-course-chicken-mutton",
    name: "Chicken & Mutton Curries",
    description: "Rich traditional gravies, butter chicken, kadhai mutton, and kormas.",
    icon: "Soup",
    displayOrder: 5,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-veg-main",
    slug: "main-course-veg",
    name: "Vegetarian Main Course",
    description: "Paneer butter masala, dal tadka, mushroom pepper fry, and fresh seasonal curries.",
    icon: "Salad",
    displayOrder: 6,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-seafood",
    slug: "seafood-fish",
    name: "Seafood & Fish",
    description: "Fresh coastal fish curries, prawn masala, fish fingers, and tandoor fish.",
    icon: "Fish",
    displayOrder: 7,
    image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-breads",
    slug: "breads-kulchas",
    name: "Tandoori Breads & Naan",
    description: "Fresh butter naans, garlic naans, laccha parathas, and stuffed kulchas.",
    icon: "Wheat",
    displayOrder: 8,
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-chinese",
    slug: "chinese-noodles-rice",
    name: "Chinese & Chopsuey",
    description: "Schezwan fried rice, hakka noodles, crispy chopsueys, and wok dishes.",
    icon: "Boxes",
    displayOrder: 9,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-soups",
    slug: "soups",
    name: "Soups & Salads",
    description: "Hot & sour, sweet corn, manchow soups, and fresh green salads.",
    icon: "Coffee",
    displayOrder: 10,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
  {
    id: "cat-beverages",
    slug: "beverages-shakes-mocktails",
    name: "Beverages, Mocktails & Shakes",
    description: "Dream Love signature mocktails, thick milkshakes, cold coffee, fresh juices, and teas.",
    icon: "GlassWater",
    displayOrder: 11,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    isActive: true,
  },
];

// Complete Client Canonical Menu Dataset (100% Real Prices & Unpriced Portions Preserved)
const RAW_INITIAL_MENU_ITEMS: MenuItem[] = [
  // -------------------------------------------------------------
  // 1. DREAM LOVE SPECIAL / SIDES
  // -------------------------------------------------------------
  {
    id: "m-sp-1",
    name: "Chicken Vorta",
    canonicalName: "Chicken Bharta",
    category: "chef-specials",
    subcategory: "Special Gravy",
    description: "Signature shredded chicken cooked in rich egg-infused velvety gravy.",
    price: 180,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 1,
  },
  {
    id: "m-sp-2",
    name: "Tandoori Chicken Masala (H/F)",
    canonicalName: "Tandoori Chicken Masala",
    category: "chef-specials",
    subcategory: "Tandoori Gravy",
    description: "Charcoal grilled tandoori chicken simmered in a spiced tomato-butter gravy.",
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 2,
  },
  {
    id: "m-sp-3",
    name: "Tandoori Butter Chicken (H/F)",
    canonicalName: "Tandoori Butter Chicken",
    category: "chef-specials",
    subcategory: "Tandoori Gravy",
    description: "Classic creamy butter chicken infused with tandoori charcoal smokiness.",
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 3,
  },
  {
    id: "m-sp-4",
    name: "Tandoori Kadai Chicken (H/F)",
    canonicalName: "Tandoori Kadhai Chicken",
    category: "chef-specials",
    subcategory: "Tandoori Gravy",
    description: "Wok-cooked tandoori chicken with freshly ground coriander and bell peppers.",
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 4,
  },
  {
    id: "m-sp-5",
    name: "Tandoori Do Piyaza (H/F)",
    canonicalName: "Tandoori Chicken Do Pyaza",
    category: "chef-specials",
    subcategory: "Tandoori Gravy",
    description: "Chicken prepared with caramelized onions, spices, and tandoori aroma.",
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 5,
  },
  {
    id: "m-sp-6",
    name: "Paper Tandoori Chicken (H/F)",
    canonicalName: "Paper Tandoori Chicken",
    category: "chef-specials",
    subcategory: "Tandoor Special",
    description: "Crisp thin-crust spiced tandoori chicken cooked to golden perfection.",
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 6,
  },
  {
    id: "m-sp-7",
    name: "Kadai Mutton",
    canonicalName: "Kadhai Mutton",
    category: "main-course-chicken-mutton",
    subcategory: "Mutton Special",
    description: "Tender mutton pieces tossed in aromatic kadhai spices and rich masala.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 7,
  },
  {
    id: "m-sp-8",
    name: "Egg Vurgi Masala",
    canonicalName: "Egg Bhurji Masala",
    category: "chef-specials",
    subcategory: "Egg Special",
    description: "Spiced scrambled eggs cooked with chopped onions, green chillies, and tomatoes.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 8,
  },
  {
    id: "m-sp-9",
    name: "Chicken Kornamdom",
    canonicalName: "Chicken Kornamdom",
    category: "chef-specials",
    subcategory: "House Special",
    description: "House special chicken preparation with unique chef spices.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: false,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 9,
  },
  {
    id: "m-sp-10",
    name: "Chicken Chattanar",
    canonicalName: "Chicken Chettinad",
    category: "chef-specials",
    subcategory: "Regional Special",
    description: "Fiery regional chicken curry spiced with roasted black pepper and coconut.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isSpicy: true,
    ownerVerified: false,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 10,
  },
  {
    id: "m-sp-11",
    name: "Handi Chicken",
    canonicalName: "Handi Chicken",
    category: "main-course-chicken-mutton",
    subcategory: "Traditional Handi",
    description: "Slow-cooked chicken in an earthen handi with sealed spices.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: false,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 11,
  },
  {
    id: "m-sp-12",
    name: "Punjabi Chicken",
    canonicalName: "Punjabi Chicken Curry",
    category: "main-course-chicken-mutton",
    subcategory: "Punjabi Gravy",
    description: "Homestyle rich North Indian chicken curry simmered with whole garam masalas.",
    price: 180,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 12,
  },

  // -------------------------------------------------------------
  // 2. SALADS
  // -------------------------------------------------------------
  {
    id: "m-sal-1",
    name: "Cucumber Salad",
    category: "soups",
    subcategory: "Salad",
    description: "Freshly sliced crunchy cucumbers with lemon and chaat seasoning.",
    price: 30,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 13,
  },
  {
    id: "m-sal-2",
    name: "Onion Salad",
    category: "soups",
    subcategory: "Salad",
    description: "Crisp onion rings tossed with green chillies and freshly squeezed lemon.",
    price: 30,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 14,
  },
  {
    id: "m-sal-3",
    name: "Green Salad",
    category: "soups",
    subcategory: "Salad",
    description: "Assortment of fresh cucumbers, tomatoes, carrots, and onions.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 15,
  },
  {
    id: "m-sal-4",
    name: "Chinese Salad",
    canonicalName: "Chinese Tossed Salad",
    category: "soups",
    subcategory: "Salad",
    description: "Shredded cabbage and bell peppers tossed with spicy tangy Asian vinaigrette.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 16,
  },
  {
    id: "m-sal-5",
    name: "Fruit Salad",
    category: "soups",
    subcategory: "Salad",
    description: "Seasonal fresh fruits diced and seasoned with sweet & tangy spices.",
    price: 140,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 17,
  },

  // -------------------------------------------------------------
  // 3. MOCKTAILS & REFRESHING DRINKS
  // -------------------------------------------------------------
  {
    id: "m-dr-1",
    name: "Blue Lemonade Mocktail",
    category: "beverages-shakes-mocktails",
    subcategory: "Mocktail",
    description: "Refreshing sparkling blue curacao cooler with fresh lemon squeeze.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 18,
  },
  {
    id: "m-dr-2",
    name: "Green Lemonade Mocktail",
    category: "beverages-shakes-mocktails",
    subcategory: "Mocktail",
    description: "Cooling green apple and mint infused sparkling lemonade.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 19,
  },
  {
    id: "m-dr-3",
    name: "Masala Cold Drinks",
    category: "beverages-shakes-mocktails",
    subcategory: "Mocktail",
    description: "Chilled soda spiked with roasted cumin, black salt, and tangy lemon.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 20,
  },
  {
    id: "m-dr-4",
    name: "Orange Mocktail",
    category: "beverages-shakes-mocktails",
    subcategory: "Mocktail",
    description: "Citrusy orange fizz blended with mint and crushed ice.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 21,
  },
  {
    id: "m-dr-5",
    name: "Dream Love Special Mocktail",
    category: "beverages-shakes-mocktails",
    subcategory: "Mocktail",
    description: "Signature cafe layered tropical fruit fusion with effervescent sparkle.",
    price: 110,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 22,
  },

  // -------------------------------------------------------------
  // 4. SHAKES & COLD COFFEES
  // -------------------------------------------------------------
  {
    id: "m-sh-1",
    name: "Butter Scotch Shake",
    category: "beverages-shakes-mocktails",
    subcategory: "Shakes",
    description: "Thick creamy milkshake with crunchy butterscotch bits and caramel drizzle.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 23,
  },
  {
    id: "m-sh-2",
    name: "Oreo Shake",
    category: "beverages-shakes-mocktails",
    subcategory: "Shakes",
    description: "Blended Oreo cookies in thick vanilla cream milk.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 24,
  },
  {
    id: "m-sh-3",
    name: "Chocolate Shake",
    category: "beverages-shakes-mocktails",
    subcategory: "Shakes",
    description: "Rich velvety chocolate blended with ice cream and cocoa.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 25,
  },
  {
    id: "m-sh-4",
    name: "Sarja Shake",
    canonicalName: "Sharjah Shake",
    category: "beverages-shakes-mocktails",
    subcategory: "Shakes",
    description: "Classic South-Indian style rich fruit & horlicks milkshake.",
    price: 140,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 26,
  },
  {
    id: "m-sh-5",
    name: "Cold Coffee",
    category: "beverages-shakes-mocktails",
    subcategory: "Coffee",
    description: "Freshly brewed espresso shaken cold with creamy milk and cocoa dusting.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 27,
  },
  {
    id: "m-sh-6",
    name: "Cold Coffee With Ice Cream",
    category: "beverages-shakes-mocktails",
    subcategory: "Coffee",
    description: "Decadent cold coffee topped with a generous scoop of vanilla ice cream.",
    price: 170,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 28,
  },
  {
    id: "m-sh-7",
    name: "Faluda",
    canonicalName: "Royal Falooda",
    category: "beverages-shakes-mocktails",
    subcategory: "Dessert Beverage",
    description: "Layered rose syrup, vermicelli, sabja seeds, milk, and ice cream.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 29,
  },

  // -------------------------------------------------------------
  // 5. FRESH JUICES
  // -------------------------------------------------------------
  {
    id: "m-ju-1",
    name: "Lemon Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Freshly squeezed lemon with sweet and salt options.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 30,
  },
  {
    id: "m-ju-2",
    name: "Ment Juice",
    canonicalName: "Mint Lemon Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Crushed fresh garden mint with lime and ice.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 31,
  },
  {
    id: "m-ju-3",
    name: "Watermelon Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Pure chilled watermelon juice made fresh to order.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 32,
  },
  {
    id: "m-ju-4",
    name: "Pineapple Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Freshly pressed tropical pineapple juice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 33,
  },
  {
    id: "m-ju-5",
    name: "Orange Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Sweet and tangy freshly extracted orange juice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 34,
  },
  {
    id: "m-ju-6",
    name: "Musumbi Juice",
    canonicalName: "Mosambi / Sweet Lime Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Refreshing natural sweet lime juice packed with Vitamin C.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 35,
  },
  {
    id: "m-ju-7",
    name: "Carrot Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Nutritious freshly pressed carrot juice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 36,
  },
  {
    id: "m-ju-8",
    name: "Cucumber Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Hydrating fresh cucumber juice with light seasoning.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 37,
  },
  {
    id: "m-ju-9",
    name: "Mix Juice",
    category: "beverages-shakes-mocktails",
    subcategory: "Fresh Juice",
    description: "Seasonal mix of fresh fruits pressed to a vibrant blend.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 38,
  },

  // -------------------------------------------------------------
  // 6. HOT DRINKS
  // -------------------------------------------------------------
  {
    id: "m-ht-1",
    name: "Coffee",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Steaming aromatic hot milk coffee.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 39,
  },
  {
    id: "m-ht-2",
    name: "Gream Tea",
    canonicalName: "Green Tea",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Healthy antioxidant-rich warm green tea.",
    price: 20,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 40,
  },
  {
    id: "m-ht-3",
    name: "Black Tea",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Classic brisk black tea.",
    price: 15,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 41,
  },
  {
    id: "m-ht-4",
    name: "Black Coffee",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Rich dark brewed hot coffee.",
    price: 30,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 42,
  },
  {
    id: "m-ht-5",
    name: "Ginger Tea",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Warming fresh crushed ginger tea.",
    price: 15,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 43,
  },
  {
    id: "m-ht-6",
    name: "Lemon Tea",
    category: "beverages-shakes-mocktails",
    subcategory: "Hot Drinks",
    description: "Zesty lemon infused black tea.",
    price: 15,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 44,
  },

  // -------------------------------------------------------------
  // 7. TANDOORI — NON-VEG
  // -------------------------------------------------------------
  {
    id: "m-tan-1",
    name: "Chicken Tandoori",
    category: "tandoori-kebabs",
    subcategory: "Tandoor",
    description: "Whole spring chicken marinated in Kashmiri chili, yogurt, and roasted in tandoor.",
    price: 200,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 45,
  },
  {
    id: "m-tan-2",
    name: "Chicken Tikka (H/F)",
    category: "tandoori-kebabs",
    subcategory: "Tikka",
    description: "Succulent boneless chicken chunks skewers grilled over live charcoal.",
    price: 120,
    portion: "Half / Full",
    priceType: "portion_based",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 46,
  },
  {
    id: "m-tan-3",
    name: "Tangri Kabab",
    canonicalName: "Tangdi Kebab",
    category: "tandoori-kebabs",
    subcategory: "Kebab",
    description: "Juicy chicken drumsticks marinated in rich cashew cream and spices.",
    price: 250,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 47,
  },
  {
    id: "m-tan-4",
    name: "Wings Kabab",
    category: "tandoori-kebabs",
    subcategory: "Kebab",
    description: "Spiced tandoori roasted chicken wings with lemon glaze.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 48,
  },
  {
    id: "m-tan-5",
    name: "Tandoor Fish",
    category: "seafood-fish",
    subcategory: "Tandoor Fish",
    description: "Fresh catch whole fish marinated in mustard-ajwain spices and clay oven baked.",
    portion: "As per size",
    priceType: "as_per_size",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 49,
  },
  {
    id: "m-tan-6",
    name: "Fish Tikka",
    category: "seafood-fish",
    subcategory: "Tandoor Fish",
    description: "Boneless fish cubes marinated in spiced yogurt and char-grilled.",
    portion: "As per size",
    priceType: "as_per_size",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 50,
  },
  {
    id: "m-tan-7",
    name: "Dream Love Special Chicken Kuttu Protta",
    canonicalName: "Chicken Kothu Parotta",
    category: "chef-specials",
    subcategory: "Street Special",
    description: "Shredded layered parottas wok-tossed with spicy chicken, eggs, and salna gravy.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 51,
  },
  {
    id: "m-tan-8",
    name: "Dream Love Special Pan Kabab (F)",
    canonicalName: "Dream Love Special Pan Kebab",
    category: "tandoori-kebabs",
    subcategory: "Special Kebab",
    description: "House signature pan-seared spiced kebabs served sizzling hot.",
    portion: "Full",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 52,
  },

  // -------------------------------------------------------------
  // 8. RICE & BIRYANI — VEG
  // -------------------------------------------------------------
  {
    id: "m-rv-1",
    name: "Veg Biriyani",
    canonicalName: "Veg Biryani",
    category: "biryani-rice",
    subcategory: "Veg Biryani",
    description: "Fragrant basmati rice layered with garden vegetables and saffron dum spices.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 53,
  },
  {
    id: "m-rv-2",
    name: "Paneer Biriyani",
    canonicalName: "Paneer Biryani",
    category: "biryani-rice",
    subcategory: "Veg Biryani",
    description: "Tender cottage cheese cubes dum-cooked with long grain basmati rice.",
    price: 250,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 54,
  },
  {
    id: "m-rv-3",
    name: "Alu Biriyani",
    canonicalName: "Aloo Biryani",
    category: "biryani-rice",
    subcategory: "Veg Biryani",
    description: "Authentic Bengal style biryani featuring slow-cooked spiced potatoes.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 55,
  },
  {
    id: "m-rv-4",
    name: "Steam Rice",
    category: "biryani-rice",
    subcategory: "Rice",
    description: "Steamed fluffy long-grain rice.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 56,
  },
  {
    id: "m-rv-5",
    name: "Veg Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Wok tossed basmati rice with finely diced carrots, beans, and peas.",
    price: 70,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 57,
  },
  {
    id: "m-rv-6",
    name: "Mushroom Fired Rice",
    canonicalName: "Mushroom Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Stir-fried rice with seasoned mushrooms and spring onions.",
    price: 90,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 58,
  },
  {
    id: "m-rv-7",
    name: "Paneer Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Wok-fried rice tossed with golden paneer cubes and light soy.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 59,
  },
  {
    id: "m-rv-8",
    name: "Gobi Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Cauliflower florets sautéed with spiced wok rice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 60,
  },
  {
    id: "m-rv-9",
    name: "Schezwan Veg Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Spicy red Schezwan pepper infused fried rice with veggies.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 61,
  },
  {
    id: "m-rv-10",
    name: "Sanghi Veg Fried Rice",
    canonicalName: "Shanghai Veg Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Shanghai style savoury fried rice tossed with crispy vegetable juliennes.",
    price: 110,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 62,
  },
  {
    id: "m-rv-11",
    name: "Special 3paix Veg Fried Rice",
    canonicalName: "Special Triple Veg Fried Rice",
    category: "biryani-rice",
    subcategory: "Fried Rice",
    description: "Triple layered specialty vegetarian fried rice with paneer and mushrooms.",
    price: 140,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 63,
  },
  {
    id: "m-rv-12",
    name: "Paneer Pulao",
    category: "biryani-rice",
    subcategory: "Pulao",
    description: "Mild sweet-spiced basmati pulao studded with paneer and whole spices.",
    price: 130,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 64,
  },
  {
    id: "m-rv-13",
    name: "Mix Veg Pulao",
    category: "biryani-rice",
    subcategory: "Pulao",
    description: "Fragrant pulao cooked with assorted vegetables and ghee aroma.",
    price: 150,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 65,
  },
  {
    id: "m-rv-14",
    name: "Jeera Rice",
    category: "biryani-rice",
    subcategory: "Rice",
    description: "Basmati rice tempered with golden roasted cumin seeds.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 66,
  },
  {
    id: "m-rv-15",
    name: "Ghee Rice",
    category: "biryani-rice",
    subcategory: "Rice",
    description: "Rich basmati rice enriched with pure desi ghee and mild whole spices.",
    price: 110,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 67,
  },

  // -------------------------------------------------------------
  // 9. RICE & BIRYANI — NON-VEG
  // -------------------------------------------------------------
  {
    id: "m-rnv-1",
    name: "Dream Love Special Handi Chicken Biriyani",
    canonicalName: "Special Handi Chicken Biryani",
    category: "biryani-rice",
    subcategory: "Non-Veg Biryani",
    description: "House signature dum biryani sealed and cooked in clay handi with tender chicken.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 68,
  },
  {
    id: "m-rnv-2",
    name: "Chicken Biriyani",
    canonicalName: "Chicken Biryani",
    category: "biryani-rice",
    subcategory: "Non-Veg Biryani",
    description: "Classic spiced chicken biryani with aromatic basmati rice and savory spices.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 69,
  },
  {
    id: "m-rnv-3",
    name: "Mutton Biriyani",
    canonicalName: "Mutton Biryani",
    category: "biryani-rice",
    subcategory: "Non-Veg Biryani",
    description: "Tender goat meat slow-cooked with spiced long-grain saffron basmati.",
    price: 220,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 70,
  },
  {
    id: "m-rnv-4",
    name: "Egg Biriyani",
    canonicalName: "Egg Biryani",
    category: "biryani-rice",
    subcategory: "Non-Veg Biryani",
    description: "Golden fried spiced eggs nestled in fragrant dum biryani rice.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 71,
  },
  {
    id: "m-rnv-5",
    name: "Egg Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Fluffy scrambled eggs wok-tossed with rice, vegetables, and light pepper.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 72,
  },
  {
    id: "m-rnv-6",
    name: "Chicken Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Tender boneless chicken strips and egg tossed in Chinese wok rice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 73,
  },
  {
    id: "m-rnv-7",
    name: "Mix Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Combination of chicken, egg, and fresh vegetables tossed together.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 74,
  },
  {
    id: "m-rnv-8",
    name: "Prawn Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Juicy prawns stir-fried with basmati rice, scallions, and soy.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 75,
  },
  {
    id: "m-rnv-9",
    name: "Schezwan Egg Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Fiery Schezwan sauce tossed with eggs, veggies, and rice.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 76,
  },
  {
    id: "m-rnv-10",
    name: "Schezwan Mix Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Spicy Schezwan fried rice loaded with chicken, prawns, and egg.",
    price: 140,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 77,
  },
  {
    id: "m-rnv-11",
    name: "Saanghi Mix Fried Rice",
    canonicalName: "Shanghai Mixed Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Shanghai style savory fried rice with mixed meats.",
    price: 150,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 78,
  },
  {
    id: "m-rnv-12",
    name: "Sp 3 Pal X Fried Rice",
    canonicalName: "Special Triple Non-Veg Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Special triple non-veg wok rice with gravy.",
    price: 180,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 79,
  },
  {
    id: "m-rnv-13",
    name: "Mutton Fried Rice",
    category: "biryani-rice",
    subcategory: "Non-Veg Fried Rice",
    description: "Succulent shredded mutton stir-fried with fragrant basmati.",
    price: 220,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 80,
  },

  // -------------------------------------------------------------
  // 10. BREAD ITEMS & KULCHAS
  // -------------------------------------------------------------
  {
    id: "m-br-1",
    name: "Lacha Paratha",
    canonicalName: "Laccha Paratha",
    category: "breads-kulchas",
    subcategory: "Paratha",
    description: "Multi-layered flaky griddle paratha.",
    price: 12,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 81,
  },
  {
    id: "m-br-2",
    name: "Tandoori Lacha Paratha",
    canonicalName: "Tandoori Laccha Paratha",
    category: "breads-kulchas",
    subcategory: "Paratha",
    description: "Crispy layered paratha baked in clay tandoor.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 82,
  },
  {
    id: "m-br-3",
    name: "Tandoori Roti",
    category: "breads-kulchas",
    subcategory: "Roti",
    description: "Whole wheat unleavened bread baked crisp in tandoor.",
    price: 15,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 83,
  },
  {
    id: "m-br-4",
    name: "Tandoori Butter Roti",
    category: "breads-kulchas",
    subcategory: "Roti",
    description: "Clay-oven roti brushed generously with butter.",
    price: 25,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 84,
  },
  {
    id: "m-br-5",
    name: "Tandoori Plain Nan",
    canonicalName: "Plain Naan",
    category: "breads-kulchas",
    subcategory: "Naan",
    description: "Soft leavened refined flour flatbread.",
    price: 25,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 85,
  },
  {
    id: "m-br-6",
    name: "Tandoori Butter Nan",
    canonicalName: "Butter Naan",
    category: "breads-kulchas",
    subcategory: "Naan",
    description: "Soft tandoori naan glazed with melted golden butter.",
    price: 30,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 86,
  },
  {
    id: "m-br-7",
    name: "Garlic Nan",
    canonicalName: "Garlic Naan",
    category: "breads-kulchas",
    subcategory: "Naan",
    description: "Tandoor naan topped with minced roasted garlic and fresh coriander.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 87,
  },
  {
    id: "m-br-8",
    name: "Butter Garlic Nan",
    canonicalName: "Butter Garlic Naan",
    category: "breads-kulchas",
    subcategory: "Naan",
    description: "Garlic naan brushed with hot melted butter.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 88,
  },
  {
    id: "m-br-9",
    name: "Plain Kulcha",
    category: "breads-kulchas",
    subcategory: "Kulcha",
    description: "Mildly leavened traditional Punjabi flatbread.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 89,
  },
  {
    id: "m-br-10",
    name: "Butter Kulcha",
    category: "breads-kulchas",
    subcategory: "Kulcha",
    description: "Soft kulcha finished with fresh butter glaze.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 90,
  },
  {
    id: "m-br-11",
    name: "Chicken Kulcha With Butter",
    category: "breads-kulchas",
    subcategory: "Kulcha",
    description: "Stuffed spiced minced chicken kulcha topped with butter.",
    price: 70,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 91,
  },
  {
    id: "m-br-12",
    name: "Tandoori Alu Paratha",
    canonicalName: "Tandoori Aloo Paratha",
    category: "breads-kulchas",
    subcategory: "Paratha",
    description: "Clay oven roasted paratha stuffed with spiced mashed potatoes.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 92,
  },
  {
    id: "m-br-13",
    name: "Pach Nan",
    canonicalName: "Cheese / Peshawari Naan",
    category: "breads-kulchas",
    subcategory: "Naan",
    description: "Specialty stuffed naan baked crisp in tandoor.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 93,
  },

  // -------------------------------------------------------------
  // 11. STARTERS — VEG & NON-VEG
  // -------------------------------------------------------------
  {
    id: "m-st-1",
    name: "Paneer 65",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Crispy fried cottage cheese tossed in curry leaves, mustard seeds, and yogurt chili sauce.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 94,
  },
  {
    id: "m-st-2",
    name: "Gobi 65",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Batter-fried crunchy cauliflower tossed in southern spiced masala.",
    price: 90,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 95,
  },
  {
    id: "m-st-3",
    name: "Mushroom 65",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Button mushrooms coated in crispy spiced batter.",
    price: 90,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 96,
  },
  {
    id: "m-st-4",
    name: "Veg 65",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Mixed vegetable fritters tossed in spicy tempered sauce.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 97,
  },
  {
    id: "m-st-5",
    name: "French Fry",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Golden fried potato batons dusted with salt and seasoning.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 98,
  },
  {
    id: "m-st-6",
    name: "Tandoori Paneer Tikka",
    category: "starters-bites",
    subcategory: "Veg Starter",
    description: "Cottage cheese skewers char-grilled with peppers and onions in tandoor.",
    price: 140,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 99,
  },
  {
    id: "m-st-7",
    name: "Chicken 65",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Iconic spiced and deep-fried boneless chicken tossed with curry leaves and green chillies.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 100,
  },
  {
    id: "m-st-8",
    name: "Chicken Pakora",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Crispy gram-flour battered chicken fritters seasoned with ajwain.",
    price: 100,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 101,
  },
  {
    id: "m-st-9",
    name: "Chicken Lollipop",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Crisp frenched chicken winglets served with spicy schezwan dip.",
    price: 110,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 102,
  },
  {
    id: "m-st-10",
    name: "Chicken Schezwan Lollipop",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Chicken lollipops tossed in fiery garlic Schezwan sauce.",
    price: 120,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 103,
  },
  {
    id: "m-st-11",
    name: "Prawn 65",
    category: "seafood-fish",
    subcategory: "Seafood Starter",
    description: "Crisp golden fried prawns tossed with southern spices and curry leaves.",
    price: 150,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 104,
  },
  {
    id: "m-st-12",
    name: "Cripci Chicken",
    canonicalName: "Crispy Fried Chicken",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Crunchy fried boneless chicken strips with house dip.",
    price: 130,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 105,
  },
  {
    id: "m-st-13",
    name: "Dram Stick",
    canonicalName: "Chicken Drumstick",
    category: "starters-bites",
    subcategory: "Non-Veg Starter",
    description: "Spiced crumb-fried chicken drumsticks.",
    price: 250,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 106,
  },
  {
    id: "m-st-14",
    name: "Fish Finger",
    category: "seafood-fish",
    subcategory: "Seafood Starter",
    description: "Crumb-coated golden fish batons served with tartar sauce.",
    price: 180,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 107,
  },
  {
    id: "m-st-15",
    name: "Fish Fry",
    category: "seafood-fish",
    subcategory: "Seafood Starter",
    description: "Traditional Kolkata style seasoned crumb-fried bhetki/fish fillet.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 108,
  },

  // -------------------------------------------------------------
  // 12. EGGS & BREAKFAST BITES
  // -------------------------------------------------------------
  {
    id: "m-egg-1",
    name: "Egg Vurgi",
    canonicalName: "Egg Bhurji",
    category: "starters-bites",
    subcategory: "Egg",
    description: "Classic Indian scrambled eggs with green chillies and onions.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 109,
  },
  {
    id: "m-egg-2",
    name: "Boild Egg",
    canonicalName: "Boiled Eggs (2 pcs)",
    category: "starters-bites",
    subcategory: "Egg",
    description: "Two hard-boiled eggs served with black pepper salt.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 110,
  },
  {
    id: "m-egg-3",
    name: "Scramble Egg",
    canonicalName: "Scrambled Eggs",
    category: "starters-bites",
    subcategory: "Egg",
    description: "Butter-scrambled soft eggs with herbs.",
    price: 70,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 111,
  },
  {
    id: "m-egg-4",
    name: "Egg Poch",
    canonicalName: "Egg Poach",
    category: "starters-bites",
    subcategory: "Egg",
    description: "Pan-poached egg with runny yolk and spices.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 112,
  },
  {
    id: "m-egg-5",
    name: "Omlet",
    canonicalName: "Masala Omelette",
    category: "starters-bites",
    subcategory: "Egg",
    description: "Fluffy double-egg masala omelet with onions, tomatoes, and chillies.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    isEgg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 113,
  },

  // -------------------------------------------------------------
  // 13. SOUPS — VEG & NON-VEG
  // -------------------------------------------------------------
  {
    id: "m-spv-1",
    name: "Sweet Corn Veg Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Comforting sweet corn broth with tender kernels and vegetables.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 114,
  },
  {
    id: "m-spv-2",
    name: "Hot And Sour Veg Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Tangy and spicy pepper soup with finely chopped vegetables and tofu.",
    price: 55,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 115,
  },
  {
    id: "m-spv-3",
    name: "Veg Clear Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Light and healthy vegetable broth infused with ginger and cilantro.",
    price: 40,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 116,
  },
  {
    id: "m-spv-4",
    name: "Veg Manchow Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Hearty garlic-chili vegetable soup served with crispy fried noodles.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 117,
  },
  {
    id: "m-spv-5",
    name: "Cream Of Mushroom Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Velvety smooth pureed mushroom soup enriched with fresh cream.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 118,
  },
  {
    id: "m-spv-6",
    name: "Tomato Soup",
    category: "soups",
    subcategory: "Veg Soup",
    description: "Classic ripe tomato soup served with golden butter croutons.",
    price: 50,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 119,
  },
  {
    id: "m-spnv-1",
    name: "Sweet Corn Chicken Veg Soup",
    canonicalName: "Sweet Corn Chicken Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Creamy corn broth with shredded chicken and egg ribbons.",
    price: 75,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 120,
  },
  {
    id: "m-spnv-2",
    name: "Hot And Sour Chicken Veg Soup",
    canonicalName: "Hot & Sour Chicken Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Fiery spicy and tangy chicken soup with vegetables and egg.",
    price: 75,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 121,
  },
  {
    id: "m-spnv-3",
    name: "Chicken Clear Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Clear simmered chicken broth with diced chicken and fresh greens.",
    price: 60,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 122,
  },
  {
    id: "m-spnv-4",
    name: "Chicken Manchow Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Spicy dark broth loaded with minced chicken, garlic, and crispy fried noodles.",
    price: 80,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    isSpicy: true,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 123,
  },
  {
    id: "m-spnv-5",
    name: "Cream Of Chicken Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Rich and smooth cream soup with shredded tender chicken breast.",
    price: 85,
    priceType: "fixed",
    isAvailable: true,
    isFeatured: false,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "verified",
    source: "Client Menu",
    displayOrder: 124,
  },
  {
    id: "m-spnv-6",
    name: "Mutton Soup",
    category: "soups",
    subcategory: "Non-Veg Soup",
    description: "Slow-simmered bone broth with aromatic whole spices.",
    priceType: "unpriced",
    portion: "Ask for price",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 125,
  },

  // -------------------------------------------------------------
  // 14. VEG MAIN COURSE (CURRIES & GRAVIES)
  // -------------------------------------------------------------
  {
    id: "m-vgc-1",
    name: "Paneer Butter Masala",
    category: "main-course-veg",
    subcategory: "Paneer Gravy",
    description: "Soft cottage cheese simmered in a velvety sweet-spiced tomato, cashew and butter gravy.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 126,
  },
  {
    id: "m-vgc-2",
    name: "Paneer Masala",
    category: "main-course-veg",
    subcategory: "Paneer Gravy",
    description: "Cottage cheese cooked in an onion-tomato masala with fresh coriander.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 127,
  },
  {
    id: "m-vgc-3",
    name: "Mushroom Masala",
    category: "main-course-veg",
    subcategory: "Mushroom Gravy",
    description: "Plump button mushrooms cooked in spiced aromatic onion-tomato gravy.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 128,
  },
  {
    id: "m-vgc-4",
    name: "Mushroom Butter Masala",
    category: "main-course-veg",
    subcategory: "Mushroom Gravy",
    description: "Tender mushrooms cooked in buttery tomato-cashew sauce.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 129,
  },
  {
    id: "m-vgc-5",
    name: "Dal Tadka",
    category: "main-course-veg",
    subcategory: "Dal",
    description: "Yellow lentils tempered with ghee, cumin seeds, garlic, and dried red chillies.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 130,
  },
  {
    id: "m-vgc-6",
    name: "Dal Fry",
    category: "main-course-veg",
    subcategory: "Dal",
    description: "Comforting yellow dal simmered with onions, tomatoes, and ginger.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 131,
  },
  {
    id: "m-vgc-7",
    name: "Aloo Jeera Fry",
    category: "main-course-veg",
    subcategory: "Dry Veg",
    description: "Diced potatoes sautéed with roasted cumin seeds and turmeric.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: false,
    isVeg: true,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 132,
  },

  // -------------------------------------------------------------
  // 15. NON-VEG CHOPSUEY & NOODLES
  // -------------------------------------------------------------
  {
    id: "m-ch-1",
    name: "Chinese Chopsuey",
    category: "chinese-noodles-rice",
    subcategory: "Chopsuey",
    description: "Crispy fried noodles topped with seasoned chicken, egg, and stir-fried vegetables in savory sauce.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 133,
  },
  {
    id: "m-ch-2",
    name: "American Chopsuey",
    category: "chinese-noodles-rice",
    subcategory: "Chopsuey",
    description: "Crispy noodle nest topped with sweet & tangy chicken-egg sauce and fried egg crown.",
    portion: "Ask for price",
    priceType: "unpriced",
    isAvailable: true,
    isFeatured: true,
    isVeg: false,
    ownerVerified: true,
    dataQualityStatus: "owner_review_required",
    source: "Client Menu",
    displayOrder: 134,
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = RAW_INITIAL_MENU_ITEMS.map(enhanceMenuItemWithImage);
